// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GrpcData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GrpcData.proto</summary>
public static partial class GrpcDataReflection {

  #region Descriptor
  /// <summary>File descriptor for GrpcData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GrpcDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5HcnBjRGF0YS5wcm90byIvCghHcnBjRGF0YRISCgpzdHJpbmdEYXRhGAEg",
          "ASgJEg8KB2ludERhdGEYAiABKANiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GrpcData), global::GrpcData.Parser, new[]{ "StringData", "IntData" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GrpcData : pb::IMessage<GrpcData> {
  private static readonly pb::MessageParser<GrpcData> _parser = new pb::MessageParser<GrpcData>(() => new GrpcData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<GrpcData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GrpcDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GrpcData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GrpcData(GrpcData other) : this() {
    stringData_ = other.stringData_;
    intData_ = other.intData_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public GrpcData Clone() {
    return new GrpcData(this);
  }

  /// <summary>Field number for the "stringData" field.</summary>
  public const int StringDataFieldNumber = 1;
  private string stringData_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string StringData {
    get { return stringData_; }
    set {
      stringData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "intData" field.</summary>
  public const int IntDataFieldNumber = 2;
  private long intData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long IntData {
    get { return intData_; }
    set {
      intData_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as GrpcData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(GrpcData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (StringData != other.StringData) return false;
    if (IntData != other.IntData) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (StringData.Length != 0) hash ^= StringData.GetHashCode();
    if (IntData != 0L) hash ^= IntData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (StringData.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(StringData);
    }
    if (IntData != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(IntData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (StringData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(StringData);
    }
    if (IntData != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(IntData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(GrpcData other) {
    if (other == null) {
      return;
    }
    if (other.StringData.Length != 0) {
      StringData = other.StringData;
    }
    if (other.IntData != 0L) {
      IntData = other.IntData;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          StringData = input.ReadString();
          break;
        }
        case 16: {
          IntData = input.ReadInt64();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
